# ./Web_Toolkit/browser_diagnostics/src/python/browser_diagnostics/main.py
"""Command runner for portable browser diagnostics Python Playwright checks."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

from runner import run_browser_diagnostics


def parse_args() -> argparse.Namespace:
    """Parse CLI flags for the Python browser-diagnostics worker."""

    parser = argparse.ArgumentParser(description="Portable browser diagnostics Playwright worker")
    parser.add_argument("--config", required=True, help="Path to the JSON config file generated by the Node CLI")
    return parser.parse_args()


def load_config(config_path: str) -> dict:
    """Load the browser-diagnostics config JSON."""

    return json.loads(Path(config_path).read_text(encoding="utf-8"))


def write_report(report: dict, output_path: str) -> None:
    """Write the raw Python browser-diagnostics report."""

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def main() -> int:
    """Run the Python Playwright browser-diagnostics worker."""

    args = parse_args()
    config = load_config(args.config)
    output_path = str(config.get("jsonOut") or "")
    if not output_path:
        raise SystemExit("Missing jsonOut in browser diagnostics config.")
    try:
        report = run_browser_diagnostics(config)
    except Exception as error:  # noqa: BLE001
        report = {
            "checkedAt": datetime.now(timezone.utc).isoformat(),
            "profile": config.get("profile", ""),
            "projectRoot": config.get("projectRoot", ""),
            "python": {
                "ok": False,
                "error": str(error),
            },
            "production": None,
            "development": None,
        }
        write_report(report, output_path)
        return 1

    write_report(report, output_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

